{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2009-4134",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "2.5"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-119"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.python.org/issue8678"
        },
        {
          "url": "http://lists.apple.com/archives/security-announce/2010//Nov/msg00000.html"
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html"
        },
        {
          "url": "http://secunia.com/advisories/42888"
        },
        {
          "url": "http://secunia.com/advisories/43068"
        },
        {
          "url": "http://secunia.com/advisories/43364"
        },
        {
          "url": "http://support.apple.com/kb/HT4435"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215"
        },
        {
          "url": "http://www.redhat.com/support/errata/RHSA-2011-0027.html"
        },
        {
          "url": "http://www.redhat.com/support/errata/RHSA-2011-0260.html"
        },
        {
          "url": "http://www.securityfocus.com/bid/40361"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2011/0122"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2011/0212"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2011/0413"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=541698"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Buffer underflow in the rgbimg module in Python 2.5 allows remote attackers to cause a denial of service (application crash) via a large ZSIZE value in a black-and-white (aka B/W) RGB image that triggers an invalid pointer dereference."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:2.5",
            "cpe23Uri": "cpe:2.3:a:python:python:2.5:*:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:N/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 10.0,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2010-05-27T19:30Z",
  "lastModifiedDate": "2011-03-01T06:57Z"
}