{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2014-1928",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python-gnupg_project",
            "product": {
              "product_data": [
                {
                  "product_name": "python-gnupg",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "0.3.5"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-20"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://seclists.org/oss-sec/2014/q1/246"
        },
        {
          "url": "http://seclists.org/oss-sec/2014/q1/294"
        },
        {
          "url": "http://secunia.com/advisories/56616"
        },
        {
          "url": "http://secunia.com/advisories/59031"
        },
        {
          "url": "http://www.debian.org/security/2014/dsa-2946"
        },
        {
          "url": "https://code.google.com/p/python-gnupg/"
        },
        {
          "url": "https://code.google.com/p/python-gnupg/issues/detail?id=98"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The shell_quote function in python-gnupg 0.3.5 does not properly escape characters, which allows context-dependent attackers to execute arbitrary code via shell metacharacters in unspecified vectors, as demonstrated using \"\\\" (backslash) characters to form multi-command sequences, a different vulnerability than CVE-2014-1927.  NOTE: this vulnerability exists because of an incomplete fix for CVE-2013-7323."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python-gnupg_project:python-gnupg",
            "cpe23Uri": "cpe:2.3:a:python-gnupg_project:python-gnupg:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "0.3.5"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:L/AC:L/Au:N/C:P/I:P/A:P)",
        "accessVector": "LOCAL",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "baseScore": 4.6
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 3.9,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2014-10-25T21:55Z",
  "lastModifiedDate": "2014-10-27T19:24Z"
}