{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2008-1679"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python_software_foundation",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "2.4"
                      },
                      {
                        "version_value": "2.5.2"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-189"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.python.org/issue1179"
        },
        {
          "url": "http://bugs.python.org/msg64682"
        },
        {
          "url": "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html"
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html"
        },
        {
          "url": "http://secunia.com/advisories/29889"
        },
        {
          "url": "http://secunia.com/advisories/29955"
        },
        {
          "url": "http://secunia.com/advisories/30872"
        },
        {
          "url": "http://secunia.com/advisories/31255"
        },
        {
          "url": "http://secunia.com/advisories/31358"
        },
        {
          "url": "http://secunia.com/advisories/31365"
        },
        {
          "url": "http://secunia.com/advisories/31518"
        },
        {
          "url": "http://secunia.com/advisories/31687"
        },
        {
          "url": "http://secunia.com/advisories/33937"
        },
        {
          "url": "http://secunia.com/advisories/38675"
        },
        {
          "url": "http://security.gentoo.org/glsa/glsa-200807-01.xml"
        },
        {
          "url": "http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289"
        },
        {
          "url": "http://support.apple.com/kb/HT3438"
        },
        {
          "url": "http://support.avaya.com/css/P8/documents/100074697"
        },
        {
          "url": "http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149"
        },
        {
          "url": "http://www.debian.org/security/2008/dsa-1551"
        },
        {
          "url": "http://www.debian.org/security/2008/dsa-1620"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2008:163"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2008:164"
        },
        {
          "url": "http://www.novell.com/support/search.do?cmd=displayKC&docType=kc&externalId=InfoDocument-patchbuilder-readme5032900"
        },
        {
          "url": "http://www.ubuntu.com/usn/usn-632-1"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/41958"
        },
        {
          "url": "https://issues.rpath.com/browse/RPL-2424"
        },
        {
          "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A10583"
        },
        {
          "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A7800"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpeMatchString": "cpe:/a:python_software_foundation:python:2.4",
            "cpe23Uri": "cpe:2.3:a:python_software_foundation:python:2.4:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpeMatchString": "cpe:/a:python_software_foundation:python",
            "cpe23Uri": "cpe:2.3:a:python_software_foundation:python:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "2.5.2"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "vectorString": "(AV:N/AC:M/Au:N/C:P/I:P/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "baseScore": 6.8
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8.6,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": true,
      "userInteractionRequired": true
    }
  },
  "publishedDate": "2008-04-22T04:41Z",
  "lastModifiedDate": "2017-09-29T01:30Z"
}