{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2012-1502",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "pypam",
            "product": {
              "product_data": [
                {
                  "product_name": "pypam",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "0.5.0"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-399"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://lists.opensuse.org/opensuse-updates/2012-04/msg00027.html"
        },
        {
          "url": "http://secunia.com/advisories/48312"
        },
        {
          "url": "http://secunia.com/advisories/48332"
        },
        {
          "url": "http://secunia.com/advisories/48746"
        },
        {
          "url": "http://ubuntu.com/usn/usn-1395-1"
        },
        {
          "url": "http://www.debian.org/security/2012/dsa-2430"
        },
        {
          "url": "http://www.lsexperts.de/advisories/lse-2012-03-01.txt"
        },
        {
          "url": "http://www.osvdb.org/79892"
        },
        {
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/73857"
        },
        {
          "url": "https://security.gentoo.org/glsa/201507-09"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Double free vulnerability in the PyPAM_conv in PAMmodule.c in PyPam 0.5.0 and earlier allows remote attackers to cause a denial of service (application crash) or possibly execute arbitrary code via a NULL byte in a password string."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:pypam:pypam",
            "cpe23Uri": "cpe:2.3:a:pypam:pypam:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "0.5.0"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:L/Au:N/C:P/I:P/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "NONE",
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "PARTIAL",
        "availabilityImpact": "PARTIAL",
        "baseScore": 7.5
      },
      "severity": "HIGH",
      "exploitabilityScore": 10.0,
      "impactScore": 6.4,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2012-06-16T00:55Z",
  "lastModifiedDate": "2017-08-29T01:31Z"
}