{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2010-3493",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "python",
            "product": {
              "product_data": [
                {
                  "product_name": "python",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "2.6"
                      },
                      {
                        "version_value": "2.7"
                      },
                      {
                        "version_value": "3.1"
                      },
                      {
                        "version_value": "3.2"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-362"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://bugs.python.org/issue6706"
        },
        {
          "url": "http://bugs.python.org/issue9129"
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2010-12/msg00006.html"
        },
        {
          "url": "http://lists.opensuse.org/opensuse-security-announce/2011-01/msg00006.html"
        },
        {
          "url": "http://secunia.com/advisories/43068"
        },
        {
          "url": "http://secunia.com/advisories/50858"
        },
        {
          "url": "http://secunia.com/advisories/51024"
        },
        {
          "url": "http://secunia.com/advisories/51040"
        },
        {
          "url": "http://svn.python.org/view/python/branches/py3k/Lib/smtpd.py?r1=84289&r2=84288&pathrev=84289"
        },
        {
          "url": "http://svn.python.org/view?view=rev&revision=84289"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:215"
        },
        {
          "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2010:216"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2010/09/09/6"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2010/09/11/2"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2010/09/22/3"
        },
        {
          "url": "http://www.openwall.com/lists/oss-security/2010/09/24/3"
        },
        {
          "url": "http://www.securityfocus.com/bid/44533"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1596-1"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1613-1"
        },
        {
          "url": "http://www.ubuntu.com/usn/USN-1613-2"
        },
        {
          "url": "http://www.vupen.com/english/advisories/2011/0212"
        },
        {
          "url": "https://bugs.launchpad.net/zodb/+bug/135108"
        },
        {
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200"
        },
        {
          "url": "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A12210"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Multiple race conditions in smtpd.py in the smtpd module in Python 2.6, 2.7, 3.1, and 3.2 alpha allow remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected return value of None, an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, or the getpeername function having an ENOTCONN error, a related issue to CVE-2010-3492."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:2.6",
            "cpe23Uri": "cpe:2.3:a:python:python:2.6:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:2.7",
            "cpe23Uri": "cpe:2.3:a:python:python:2.7:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.1",
            "cpe23Uri": "cpe:2.3:a:python:python:3.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpe22Uri": "cpe:/a:python:python:3.2:alpha",
            "cpe23Uri": "cpe:2.3:a:python:python:3.2:alpha:*:*:*:*:*:*"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "version": "2.0",
        "vectorString": "(AV:N/AC:M/Au:N/C:N/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "MEDIUM",
        "authentication": "NONE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 4.3
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8.6,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2010-10-19T20:00Z",
  "lastModifiedDate": "2017-09-19T01:31Z"
}