{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2008-7264"
    },
    "affects": {
      "vendor": {
        "vendor_data": [
          {
            "vendor_name": "g.rodola",
            "product": {
              "product_data": [
                {
                  "product_name": "pyftpdlib",
                  "version": {
                    "version_data": [
                      {
                        "version_value": "0.1"
                      },
                      {
                        "version_value": "0.1.1"
                      },
                      {
                        "version_value": "0.2.0"
                      },
                      {
                        "version_value": "0.3.0"
                      },
                      {
                        "version_value": "0.4.0"
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-20"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=71"
        },
        {
          "url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
        },
        {
          "url": "http://code.google.com/p/pyftpdlib/source/detail?r=344"
        },
        {
          "url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn344&r=344&format=side&path=/trunk/pyftpdlib/ftpserver.py"
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "operator": "OR",
        "cpe": [
          {
            "vulnerable": true,
            "cpeMatchString": "cpe:/a:g.rodola:pyftpdlib:0.1",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpeMatchString": "cpe:/a:g.rodola:pyftpdlib:0.1.1",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpeMatchString": "cpe:/a:g.rodola:pyftpdlib:0.2.0",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpeMatchString": "cpe:/a:g.rodola:pyftpdlib:0.3.0",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:*"
          },
          {
            "vulnerable": true,
            "cpeMatchString": "cpe:/a:g.rodola:pyftpdlib",
            "cpe23Uri": "cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:*",
            "versionEndIncluding": "0.4.0"
          }
        ]
      }
    ]
  },
  "impact": {
    "baseMetricV2": {
      "cvssV2": {
        "vectorString": "(AV:N/AC:L/Au:S/C:N/I:N/A:P)",
        "accessVector": "NETWORK",
        "accessComplexity": "LOW",
        "authentication": "SINGLE",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 4.0
      },
      "severity": "MEDIUM",
      "exploitabilityScore": 8.0,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainUserPrivilege": false,
      "obtainOtherPrivilege": false,
      "userInteractionRequired": false
    }
  },
  "publishedDate": "2010-10-19T20:00Z",
  "lastModifiedDate": "2010-10-20T04:00Z"
}